### ISSUE TITLE
20-files-present-and-referenced parse errors

### ISSUE THREAD

**Issue by olafhering** [openSUSE/obs-service-source_validator#12]
/usr/lib/obs/service/source_validators/20-files-present-and-referenced
fails if the spec file starts with a macro instead of some rpm tag.

%something
Version: 1.2.3

vs.

Version 1.2.3
%something

The first variant fails, the second succeeds. Please fix the tool.
https://build.opensuse.org/request/show/258106

**Comment by marcus-h** [comment]
This is fixed by PR #39 (just a side-effect of the PR, though).

**Comment by scarabeusiv** [comment]
PR #39 was merged.
