### ISSUE TITLE
source_validator ERRs on 'patch not applied' (when commented in form %patch -P 2)

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/obs-service-source_validator#136]
Ran into this as part of preparing libappindicator for RPM 4.20

The spec file has:

```
Name:           libappindicator%{?nsuffix}
Version:        12.10.1~bzr20200706.298
…
Patch2:         xappstatusicon.patch
…
%prep
%setup -q -c -n libappindicator-%{version}
#%%patch2 -p1
```

With this format, source_validator returns:
```
> osc service ra source_validator
(W) libappindicator.spec: patch 2 xappstatusicon.patch: mentioned in specfile but not applied via %patch
```

Changing the comment to `#%%patch -P 2 -p1` (to follow the format used newly, which allows to simply uncomment the line) results in

```
> osc service ra source_validator
ERROR: libappindicator.spec: patch 2 xappstatusicon.patch apparently not applied (or not applied via %patch)
Aborting: service call failed:  /usr/lib/obs/service/source_validator --outdir /home/dimstar/Documents/osc/home:dimstar:Factory/libappindicator/tmpc5i08_5t.source_validator.service
```

The most important is the change from Warning to Error - and the factory-review-bot considers Errors as fatal and declines the requests

**Comment by DimStar77** [comment]
> In any case, this issue belongs in https://github.com/openSUSE/obs-service-source_validator/issues

doh! power of habit.. was indeed supposed to be there; moved now

**Comment by Vogtinator** [comment]
Is it as simple as this?

```diff
diff --git a/helpers/check_patches_applied b/helpers/check_patches_applied
index 5a1e12b..a01d38e 100755
--- a/helpers/check_patches_applied
+++ b/helpers/check_patches_applied
@@ -45,7 +45,7 @@ while (<>) {
    if (/^%auto(?:setup|patch)\b/) { # automatically applies all patches
        exit(0);
    }
-   if (/^([#\s]*)?%[Pp]atch/ || /^#[Pp]atch/) {
+   if (/^([#\s]*)?%%?[Pp]atch/ || /^#[Pp]atch/) {
        my $applied = (/^#/) ? 2 :1;
        my @line = split (/\s+/,$_);
        my $had_P = grep {/^-P/} @line;
```

**Comment by DimStar77** [comment]
> Is it as simple as this?
> 
> ```diff
> diff --git a/helpers/check_patches_applied b/helpers/check_patches_applied
> index 5a1e12b..a01d38e 100755
> --- a/helpers/check_patches_applied
> +++ b/helpers/check_patches_applied
> @@ -45,7 +45,7 @@ while (<>) {
>     if (/^%auto(?:setup|patch)\b/) { # automatically applies all patches
>         exit(0);
>     }
> -   if (/^([#\s]*)?%[Pp]atch/ || /^#[Pp]atch/) {
> +   if (/^([#\s]*)?%%?[Pp]atch/ || /^#[Pp]atch/) {
>         my $applied = (/^#/) ? 2 :1;
>         my @line = split (/\s+/,$_);
>         my $had_P = grep {/^-P/} @line;
> ```

Unortunately no.. I had the same idea

with this patch, we get these results:

with `# %%patch -P2`
```
> osc service ra source_validator
(W) libappindicator.spec: patch 2 xappstatusicon.patch is commented out
```

with `#%%patch2`
```
> osc service ra source_validator
ERROR: libappindicator.spec: patch 2 xappstatusicon.patch apparently not applied (or not applied via %patch)

```

This basically just inverts the fail-case (invalidating not-yet converted spec files)

**Comment by Vogtinator** [comment]
Turns out it it ignores patch 0 due to a bug... I'll make a PR
