### ISSUE TITLE
Shouldn't complain about missing files if source is URL and there is a tar_scm service reference

### ISSUE THREAD

**Issue by krig** [openSUSE/obs-service-source_validator#16]
I want to set up my project like the osc project on OBS, where there is no explicit tarball in the project but in the _service file, there is a call to tar_scm which pulls the latest git master when tickled.

However, if I try to submit this to OBS without any tarball and a Source0: reference which points to the upstream stable release, I get an error like this:

```
(E) notmuch-0.19.tar.gz mentioned in spec file does not exist.
```

`source_validator` should recognize that notmuch-0.19.tar.gz isn't needed since the tarball will be fetched by the service call.

**Comment by adrianschroeter** [comment]
The source_validator is used for the policies in openSUSE:Factory.

So you should either follow it's advise, if your plan is to submit it there.

Or you should not configure your project/package to use it.

**Comment by krig** [comment]
Yeah, I figured out that I'm trying to do something I shouldn't, and it works better if I set my services as disabled and run them locally instead.

So maybe my request then is a clearer error message from source_validator? Maybe it could check the _service file first and warn that non-disabled/localrun services are not permitted by openSUSE policy?

**Comment by adrianschroeter** [comment]
yes, sounds like a plan :)
