### ISSUE TITLE
Package with existing license declined

### ISSUE THREAD

**Issue by rombert** [openSUSE/obs-service-source_validator#24]
I have recently submitted [SR #329513](https://build.opensuse.org/request/show/329513) for the icinga2 package and factory-auto declined with the following message:
 
> icinga2.spec does not appear to contain a Copyright comment. Please stick to the format
>  
>  # Copyright (c) 2011 Stephan Kulow
>  
>  or use osc service localrun format_spec_file

The spec file is shared with upstream and contains a copyright statement

    # * Copyright (C) 2012-2015 Icinga Development Team (http://www.icinga.org)    *

Can the script be adjusted to accept this form of copyright header as well?

**Comment by coolo** [comment]
the code is not in the source validator, but in the source checker (slightly different tool - maintained in osc-plugin-factory)
