### ISSUE TITLE
source validator fails on openSUSE:Factory/coreutils

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/obs-service-source_validator#55]
oS:F coreutils has two spec files (coreutils.spec and coreuitls-testsuite.spec)

the Source: lines are conditionalized based on the value of %{name} -> full URL, with %{name} if it's coreutils and simplified coreutils.tar.xz

```
%if "%{name}" == "coreutils"
# For upgrading you now just need to increase the version, remove the old
# tarballs, then run osc service localrun download_files, osc addremove,
# osc vc and osc ci and you are done.
Source0:        https://ftp.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz
Source1:        https://ftp.gnu.org/gnu/%{name}/%{name}-%{version}.tar.xz.sig
Source2:        https://savannah.gnu.org/project/memberlist-gpgkeys.php?group=%{name}&download=1&file=./%{name}.keyring
%else
# In "coreutils-testsuite", we use the version controlled file from "coreutils".
# otherwise that file would be downloaded twice during the above mentioned
# upgrade procedure.
Source0:        coreutils-%{version}.tar.xz
Source1:        coreutils-%{version}.tar.xz.sig
Source2:        coreutils.keyring
%endif
```

source-valditor now complains that:

```
(E) coreutils-testsuite.keyring mentioned in spec file is not tracked.
(E) coreutils-testsuite-8.27.tar.xz.sig mentioned in spec file is not tracked.
(E) coreutils-testsuite-8.27.tar.xz mentioned in spec file is not tracked.
```

Which is nonsense - neither of the two .spec files references this file name

**Comment by scarabeusiv** [comment]
This looks like it expands the block even for the %if %{name} == coreutils which is as written in https://github.com/openSUSE/obs-service-source_validator/blob/master/helpers/spec_query#L24

Now the question is how the parser should properly recognise this because we probably can't allow ourselves to expand the whole spec to evaluate conditions...

**Comment by marcus-h** [comment]
On 2017-09-12 01:25:56 -0700, Tomáš Chvátal wrote:
> Assigned #55 to @marcus-h.
> 
Sorry for the delay... I'm on it.

**Comment by DimStar77** [comment]
might be worthy to look into things like bubblewrap  - and actually allow full parsing (in a container; much cheaper than a VM)

#56 is a similar error introduced probably at the same time

**Comment by DimStar77** [comment]
(in case of interest, the simplest starting point to experiment with bwrap would be something like:

> bwrap  --ro-bind /usr /usr --ro-bind /bin /bin --ro-bind /lib64 /lib64 --proc /proc /bin/bash

)

which starts a bash shell in a bubblewrap container

**Comment by DimStar77** [comment]
similar error when validating glibc.spec:

```
%if !%{build_snapshot}
Source:         http://ftp.gnu.org/pub/gnu/glibc/glibc-%{version}.tar.xz
Source1:        http://ftp.gnu.org/pub/gnu/glibc/glibc-%{version}.tar.xz.sig
%else
Source:         glibc-%{version}.tar.xz
%endif
```

then source-validator complains about:

>Output of check script:
Source validator failed. Try "osc service localrun source_validator"
  Unable to extract sources from spec - spec_query failed:
  Ambiguous tags: source

**Comment by DimStar77** [comment]
ping? It's frustrating for the glibc maintainer to have his stuff decline everytime he submits something

**Comment by marcus-h** [comment]
On 2017-10-26 15:20:23 +0000, Dominique Leuenberger wrote:
> ping? It's frustrating for the glibc maintainer to have his stuff decline everytime he submits something
> 
Arghs - somehow I "lost" this issue again... The glibc error
is different from the coreutils error. For the former, we already
have code to disambiguate source tags (it just needs to be enabled
again, though). I'll come up with a PR that fixes both within the
next few days (really!). Sorry again...

**Comment by marcus-h** [comment]
On 2017-10-26 15:20:23 +0000, Dominique Leuenberger wrote:
> ping? It's frustrating for the glibc maintainer to have his stuff decline everytime he submits something
> 
I just created PR#59 [1], which fixes the glibc + coreutil issues.
It is embarrassing that this took so long... I'm sorry.

[1] https://github.com/openSUSE/obs-service-source_validator/pull/59
