### ISSUE TITLE
10-multibuild_xor_multispec contradicts documentation

### ISSUE THREAD

**Issue by StefanBruens** [openSUSE/obs-service-source_validator#79]
https://openbuildservice.org/help/manuals/obs-reference-guide/cha.obs.multibuild.html

> 7.1 Overview 
> A package source **may contain multiple build description files**.
> 2. Based on the file name of the file before the suffix. It is not important as long as just one file exists, but it has to match when multiple files exist. The name is defined by the build container name, which is **either defined in a _multibuild** directive file **or is the source package name**.

From this, I would guess it is valid to have multiple spec files not only for linked packages (matching "source package name") but also for _multibuilds, as long as the spec files have names matching the flavors, e.g.:

Package foo, flavors:
1. <main> -> foo.spec
2. bar -> foo-bar.spec
3. baz -> foo-baz.spec

This assumption is supported by the fact it actually works, see:
https://build.opensuse.org/package/show/home:StefanBruens:multibuild_example/multispec

**Comment by lnussel** [comment]
was actually discussed by coincidence with the release team and we agreed to remove the check

cc @DimStar77 @coolo
