### ISSUE TITLE
armv7hl not an included architecture

### ISSUE THREAD

**Issue by awafaa** [openSUSE/obs-service-source_validator#8]
When trying to build on ARM, source_validator errors with "Architecture is not included: armv7hl". I've not tried aarch64 yet, but if it isn't included it should be (please).

Full error is:
osc build --no-verify openSUSE_Factory_ARM armv7l xen.spec
Run source service: /usr/lib/obs/service/format_spec_file --outdir /tmp/tmpFNlO0v
Run source service: /usr/lib/obs/service/source_validator --outdir /tmp/tmp34iLvC
xen-4.4.0-testing-src.tar.bz2 stubdom.tar.bz2 qemu-xen-traditional-dir-remote.tar.bz2 qemu-xen-dir-remote.tar.bz2 seabios-dir-remote.tar.bz2 ipxe.tar.bz2 README.SuSE boot.xen boot.local.xenU init.xendomains logrotate.conf xmexample.disks block-nbd block-iscsi block-npiv-common.sh block-npiv block-npiv-vport xmclone.sh init.xen_loop xen_pvdrivers.conf kmp_filelist block-dmmd etc_pam.d_xen-api xenapiusers xen-updown.sh init.pciback sysconfig.pciback xnloader.py xencommons.service xendomains.service xen-watchdog.service init.xend xend-relocation.sh xend-relocation-server.fw domUloader.py xmexample.domUloader xmexample.disks xend.service xen-utils-0.1.tar.bz2 baselibs.conf xenalyze.hg.tar.bz2 VNC-Support-for-ExtendedKeyEvent-client-message.patch 0001-net-move-the-tap-buffer-into-TAPState.patch 0002-net-increase-tap-buffer-size.patch 0003-e1000-fix-access-4-bytes-beyond-buffer-end.patch 0004-e1000-secrc-support.patch 0005-e1000-multi-buffer-packet-support.patch 0006-e1000-clear-EOP-for-multi-buffer-descriptors.patch 0007-e1000-verify-we-have-buffers-upfront.patch 0008-e1000-check-buffer-availability.patch xen-destdir.patch xen-changeset.patch xen-xmexample.patch bridge-opensuse.patch bridge-vlan.patch bridge-bonding.patch bridge-record-creation.patch vif-bridge-no-iptables.patch vif-bridge-tap-fix.patch xl-conf-default-bridge.patch network-nat-open-SuSEfirewall2-FORWARD.patch udev-rules.patch suspend_evtchn_lock.patch xenpaging.doc.patch blktap.patch cdrom-removable.patch change-vnc-passwd.patch xen-qemu-iscsi-fix.patch qemu-security-etch1.patch xen-disable-qemu-monitor.patch xen-hvm-default-bridge.patch qemu-ifup-set-mtu.patch ioemu-vnc-resize.patch capslock_enable.patch altgr_2.patch log-guest-console.patch ioemu-blktap-fv-init.patch ioemu-blktap-image-format.patch build-tapdisk-ioemu.patch tapdisk-ioemu-logfile.patch ioemu-blktap-zero-size.patch tapdisk-ioemu-shutdown-fix.patch ioemu-blktap-barriers.patch bdrv_open2_fix_flags.patch bdrv_open2_flags_2.patch ioemu-bdrv-open-CACHE_WB.patch ioemu-7615-qcow2-fix-alloc_cluster_link_l2.patch qemu-dm-segfault.patch bdrv_default_rwflag.patch kernel-boot-hvm.patch ioemu-watchdog-support.patch ioemu-watchdog-linkage.patch ioemu-watchdog-ib700-timer.patch ioemu-hvm-pv-support.patch pvdrv_emulation_control.patch ioemu-disable-scsi.patch ioemu-disable-emulated-ide-if-pv.patch xenpaging.qemu.flush-cache.patch qemu-xen-upstream-blkif-discard.patch xen.migrate.tools_set_migration_constraints_from_cmdline.patch xen.migrate.tools_add_xm_migrate_--log_progress_option.patch xen.migrate.tools-xend_move_assert_to_exception_block.patch xen.migrate.tools_set_number_of_dirty_pages_during_migration.patch xend-config.patch xend-max-free-mem.patch xend-hvm-default-pae.patch xend-vif-route-ifup.patch xend-xenapi-console-protocol.patch xend-core-dump-loc.patch xend-xen-api-auth.patch xend-checkpoint-rename.patch xend-xm-save-check-file.patch xend-xm-create-xflag.patch xend-domu-usb-controller.patch xend-devid-or-name.patch xend-migration-domname-fix.patch xend-del_usb_xend_entry.patch xend-xen-domUloader.patch xend-multi-xvdp.patch xend-check_device_status.patch xend-change_home_server.patch xend-minimum-restart-time.patch xend-disable-internal-logrotate.patch xend-config-enable-dump-comment.patch xend-tools-watchdog-support.patch xend-console-port-restore.patch xend-vcpu-affinity-fix.patch xend-migration-bridge-check.patch xend-managed-pci-device.patch xend-hvm-firmware-passthrough.patch xend-cpuinfo-model-name.patch xend-xm-reboot-fix.patch xend-domain-lock.patch xend-domain-lock-sfex.patch xend-32on64-extra-mem.patch xend-hv_extid_compatibility.patch xend-xenpaging.autostart.patch libxen_permissive.patch xenconsole-no-multiple-connections.patch hibernate.patch stdvga-cache.patch ipxe-enable-nics.patch pygrub-netware-xnloader.patch pygrub-boot-legacy-sles.patch blktapctrl-close-fifos.patch blktapctrl-default-to-ioemu.patch blktapctrl-disable-debug-printf.patch blktap-pv-cdrom.patch set-mtu-from-bridge-for-tap-interface.patch x86-ioapic-ack-default.patch x86-cpufreq-report.patch x86-dom-print.patch x86-extra-trap-info.patch supported_module.patch magic_ioport_compat.patch disable-wget-check.patch tmp-initscript-modprobe.patch tmp_build.patch error: Architecture is not included: armv7hl
Aborting: service call failed: /usr/lib/obs/service/source_validator --outdir /tmp/tmp34iLvC
Source service run failed!

**Comment by scarabeusiv** [comment]
This is caused by rpmbuild not recognising the architecture. I seriously hope this is no longer an issue.
