### ISSUE TITLE
%elifarch is not well supported

### ISSUE THREAD

**Issue by ggardet** [openSUSE/obs-service-source_validator#85]
I encountered a weird error with `fpc.spec` file where the source validator cannot list the sources, see: https://build.opensuse.org/request/show/827517

If I drop the `--no-conditionals` flag with a manual call, it works as expected.
If I replace the `%elifarch` macro by `%else %ifarch`, it works as expected.

**Comment by DimStar77** [comment]
A minimal test case:

```
> cat test.spec 
%ifarch help
%elifarch help2
%endif

Source:         file0.zip
```

This simple .spec file ends up like:

```> /usr/lib/obs/service/source_validators/helpers/spec_query --specfile test.spec --print-sources --no-conditionals``` -> no output

(dropping ```--no-conditionals``` here outputs the sources just fine)

**Comment by dirkmueller** [comment]
https://github.com/openSUSE/obs-service-source_validator/commit/f49d8d983847f858a4b306f14886fde55a7786af has likely fixed this. feel free to reopen if there is still an issue.
